spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=samples
    username: sa
    password: 123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        proc:
          param_null_passing: true
        enable_lazy_load_no_trans: true          
server:
  port: 8080
  servlet:
    contextPath: /